### ISSUE TITLE
An unexpected error occurred when synchronising the notifications (AGAEN10.-2)

### ISSUE THREAD

**Issue by AVGP** [DP-3T/dp3t-app-android-ch#133]
I installed the application and get an error (and notification) that the "App [is] currently unable to function properly".

Model: Pixel 3 XL
OS: Android 10
Patch level: June 5,2020

**Comment by tetterl** [comment]
Same here.
`An unexpected error occurred when synchronising the notifications (AGAEN39508.-2)`

App version: 1.0.5, 1.0.0

Model: Xioami Redmi 4
Android version: 6.0.1 MMB29M
MIUI version: MIUI Global 10.2

**Comment by ludomedia** [comment]
Same error here

App version: 1.0.5, 1.0.0
Model: Galaxy S5 neo
Android: 6.0.1 MMB29K

**Comment by kunom** [comment]
Same error here: AGAEN10.-2 for a short time after reboot, then again AGAEN39508.-2 which persists.

The directions at #100 (i.e. reinstallation of the app, rebooting, check Settings > Google > Covid-19) did not help.

App version: 1.0.5 1.0.0
Model: Galaxy S5 neo
Android: 6.0.1

**Comment by SirSeto** [comment]
Same here. Reinstall does not help. 

App version 1.0.5
Model : OnePlus 6
Android : 10

**Comment by caco3** [comment]
Same on my phone (AGAEN39508.-2).
I had the pilote app now runing since several weeks and never saw this issue. Yesterday I now updated to the official release and now this morning I saw this error.
A reboot of the phone did not fix it.

My phone automatically switches to flightmode (BT, Wifi, GPRS off) in the evening and back to normal in the morning. The error was first seen in the morning when it switched the com on again.

App version: 1.0.5, 1.0.0
Model: Sony 3113
Android: 9

**Comment by simonroesch** [comment]
The error AGAEN39508 is tracked already on https://github.com/DP-3T/dp3t-app-android-ch/issues/100

This report here is about AGEN10 which is a different error. We would be very interested in bug reports to be able to see what exactly is happening and to forward them to Google. Unfortunately, Android bug reports can contain personal information, so please don't post them here. If you want to help us, see the instructions on https://developer.android.com/studio/debug/bug-report how to capture a bugreport and then send it to swisscovid@bag.admin.ch and ask them to forward it to the developer team.

**Comment by caco3** [comment]
> The error AGAEN39508 is tracked already on #100
> This report here is about AGEN10 which is a different error.

Sorry, google mislead me here with that error ID 😞

**Comment by kunom** [comment]
Another reboot today and there was again an OS update applied. No more error messages since then.

**Comment by AVGP** [comment]
Same here, reinstalled a second time, OS Update and now it's fine

**Comment by leosei** [comment]
Same error after I switch airplane mode on and then off. Only reinstalling the app fixes the issue (but then it reappears again if I go in and out of airplane mode).

**Comment by dilorenzo1987** [comment]
Same issue on my wifes Samsung Galaxy S10E

**Comment by Shallodarns** [comment]
I had the same error AGAEN39508, reinstall did not work.
I switched off the Developer Options, restarted the phone and installed the app again. Now it works

Samsung SM-G532M
Android 6.0.1
App Version: 1.0.5, 1.0.0

**Comment by simonroesch** [comment]
Thanks to everybody who helped investigating this issue! The exposureNotificationClient.provideDiagnosisKeys() sometimes results in an ApiException 10 which results in the AGAEN10 error. This is not due to a bug of the SwissCovid app but due to a bug in the ExposureNotification framework provided by Google. This will be fixed in a future version of the Google PlayServices, but we do not have a timeline yet for when this will be released. On most phones we could investigate this behaviour so far, this does not happen for all provideDiagnosisKeys()-calls and therefore the functionality of the app should not be affected, but detecting exposure will be delayed up to the next successful call to provideDiagnosisKeys().

I will keep this bug open until we have a released version of the Google PlayServices that fixes the issue.

**Comment by treki1** [comment]
Thanks Simon
I also have the error AGAEN39508.-2 on my LG G3.
According to your statement, the app works anyway and I just have to wait for the update from Google. Correct?

Danke Simon
Ich habe den Fehler AGAEN39508.-2 auch bei meinem LG G3.
Nach Deiner Aussage, funktioniert die App aber trotzdem und ich muss lediglich den Update von Google abwarten. Richtig?

**Comment by Shallodarns** [comment]
Hi Treki
Quite frankly I am not sure if its related to the update. Now I have the AGAEN10 error, so back to square one.

**Comment by simonroesch** [comment]
By now the fixed version of the Exposure Notifications framework by Google should be available on all devices. If you still observe AGAEN39508 or AGAEN10 errors, please reopen this issue.
