### ISSUE TITLE
Show the number of contacts or any other indication that the app is doing something

### ISSUE THREAD

**Issue by zukunft** [DP-3T/dp3t-app-android-ch#34]
The first version of the next-step has shown the number of contacts on the main screen. I used this  to show that the app is doing something and to check how many contacts I "created". I would recommend to include this also in the final version of the app. I know that this does not represent the "real" number of contacts, but I think any indication, that something "real" is happening would be very useful.

See also 
https://github.com/DP-3T/dp3t-app-android/issues/3
https://github.com/DP-3T/dp3t-sdk-android/issues/89

**Comment by simonroesch** [comment]
We're discussing this with UX experts, but probably won't go in this direction right now. There are several reasons:

- There is no concept of "contact" (and it cannot exist by design) and counter of handshakes is hard to understand for users.
- The revealed information can be confusing or problematic.
- It's interesting for us developers but not that important for other users .

**Comment by zukunft** [comment]
OK. Can I build my own version of the app and still connect to the "normal" backend?

**Comment by simonroesch** [comment]
Sure, it will be no problem to create a fork of the final app and display more information from the. SDK.

But one more thing: once we move to the GAEN framework, there is probably no way to get any such value anyhow...

**Comment by zukunft** [comment]
If I use "devDEBUG" for the build I still can see the details. Is it still allowed to use this for testing? E.g. overwrite my status and see how it looks on the other phones?
