### ISSUE TITLE
Cannot activate tracing on Google Piexl 3 XL

### ISSUE THREAD

**Issue by tingsu** [DP-3T/dp3t-app-android-ch#97]
I cannot activate tracing on a Google Pixel 3 XL phone. I saw simliar issues #51, but mine is reported with a totally different StatusCode.

Detailed info:

- Google Pixel 3 XL
- Android Version 9
- SwissCovid App Version 1.0.3-pilot (Installed by Google Play Store)
- Output of the command ``adb shell dumpsys activity provider - com.google.android.gms.chimera.container.GmsModuleProvider | grep 'nearby_en'``:  com.google.android.gms.nearby_en [v201817000]
- Play Services 20.18.17
- StatusCode: 39503

Screenshot:

![Screenshot_20200614-211231](https://user-images.githubusercontent.com/3156978/84602161-9a402580-ae85-11ea-8d9c-3e84f18938f6.png)

**Comment by simonroesch** [comment]
Apparently there is a problem with the nearby_en v201817000. There is a newer version available already since some time, but some devices seem to not pick it up. If this is still a problem on your device, you will probably have to wait for the next full update of the Google PlayServices. But since this is a problem of the Google PlayServices and not SwissCovid I will close this bug.
